### PR TITLE
Add Images API

### PR DESCRIPTION
**Pull request by shanecamus**

### CODE REVIEW

**Comment by ShivamJoker** [comment]
Hello Cloudflare team where are you?
This library is very much unmaintained can you please assign a member just for this?

**Comment by terinjokes** [comment]
We're working on fixing some issues with the SDK builder, but we should soon have this API (and many, many others).

**Comment by ShivamJoker** [comment]
> We're working on fixing some issues with the SDK builder, but we should soon have this API (and many, many others).

Is it going to be in TypeScript? The Go library is very much maintained and has more stars not sure why.

**Comment by terinjokes** [comment]
> Is it going to be in TypeScript?

Yes, the plan is for it to be in Typescript.

> The Go library is very much maintained and has more stars not sure why.

These projects have historically been maintained by random CF engineers as they work on other projecrs. More engineers use the Go SDK, so it has more eyeballs. This SDK is pretty much only used by me in side projects.

**Comment by terinjokes** [comment]
@Ziut3k-dev please don't spam the issues

**Pull request closed without merging**
