### PR TITLE
Add priority for MX records

### PR DESCRIPTION
**Pull request by matiboy**
Issue:
Without priority in body, adding MX returns
```
{ code: 9008,
    message: 'Invalid priority, priority must be set and be between 0 and 65535' }
```

This PR adds the priority on the `verymodel` and picks it only for MX records.
It defaults to 0 if not provided.

### CODE REVIEW

**Comment by terinjokes** [comment]
A brief glance at this it looks good. I'll look again in the morning.

**Comment by matiboy** [comment]
@terinjokes Hi, thanks for reviewing this. I just realized that this would not cover the `SRV` type of record which requires only `type` and `data` to be sent
Refer to http://stackoverflow.com/a/39031676
I'll commit a new change soon

**Comment by matiboy** [comment]
@terinjokes Given that this PR is about changing the actual body that is being POSTed, I think the tests I just added are more suitable.
Thanks

**Comment by terinjokes** [comment]
@matiboy For the moment, I'd prefer if the tests didn't use sinon to mock and that the tests match the rest of the suite.

A branch that's in progress does indeed switch to using mocks.

**Comment by matiboy** [comment]
@terinjokes Reverted to my original tests (without Sinon). Bumped version in package.json to 1.1.1

**Comment by terinjokes** [comment]
Merged as 3840803c3420ef94010e8ceddf78a4584deeec38.

**Pull request closed without merging**
