### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by kiddyfurby**
Fixed dnsRecords methods signature

### CODE REVIEW

**Comment by nolandg** [comment]
? please merge this. it's confusing without.

**Comment by terinjokes** [comment]
Merged as caf1c27b6c267af38d63cab486a9bbaa4737c93c.

Over the weekend I wrote a bunch of API docs, which will replace this section sometime this week.

**Comment by nolandg** [comment]
What are you doing working on the weekend?? :-)

I would also humbly recommend adding all the pagination options like per_page etc.

**Comment by terinjokes** [comment]
@nolandg the new docs have a pagination section.

**Comment by nolandg** [comment]
you rock

**Comment by terinjokes** [comment]
@nolandg I pushed a branch ([terin/docs](https://github.com/cloudflare/node-cloudflare/tree/terin/docs)) that contains my WIP docs. I haven't hooked up CD to deploy them, or finished them, but it should give you an idea of what the plan is.

If you have more comments or suggestions, fill free to open a new ticket. :)

**Pull request closed without merging**
