### PR TITLE
Adding support for custom hostnames

### PR DESCRIPTION
**Pull request by hsingh6764**
https://api.cloudflare.com/#custom-hostname-for-a-zone-create-custom-hostname

(Also support SSL for SaaS)

### CODE REVIEW

**Comment by hsingh6764** [comment]
@terinjokes any idea when we will have new version.

**Comment by terinjokes** [comment]
@hsingh6764 Sometime today. I won't be accepting this PR as is, but something relatively close to it.

**Comment by terinjokes** [comment]
Merged as 7607c2fd413e3c3e8460951056296c187e0b9bdc. Released in v2.3.0

**Comment by hsingh6764** [comment]
Thanks @terinjokes

**Pull request closed without merging**
