### PR TITLE
Use verymodel npm package

### PR DESCRIPTION
**Pull request by ratson**
The latest release has included the fork changes.

### CODE REVIEW

**Comment by ratson** [comment]
@terinjokes Would you have a look and see if it could be published on npm?
This remove `git` requirement from using this package.

**Comment by terinjokes** [comment]
I'm removing VeryModel entirely.

**Comment by terinjokes** [comment]
@ratson On second thought, I'd make a release of v1 that includes the changes from the current open PRs, which includes this one.

**Comment by ratson** [comment]
@terinjokes Good to hear that.

**Comment by terinjokes** [comment]
Merged as aacd5ef317eb2e5601826a92bcfedd6092b03691.

**Pull request closed without merging**
